name: DD agent

on:
  workflow_dispatch:
    inputs:
      Cluster_Type:
        description: 'Cluster Type'
        required: true
        default: 'DP'
        options:
          - 'DP'
          - 'NGC'
      Region:
        description: 'Select Region'
        required: true
        default: 'US'
        options:
          - 'US'
          - 'WE'
          - 'AU'
          - 'SG'
      Environment:
        description: 'Environment'
        required: true
        default: 'Dev'
        options:
          - 'DEV'
          - 'QA'
          - 'STG'
          - 'PRD'      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cluster Type DP | NGC
        run: |
          echo ""${{ inputs.Cluster_Type }}""
