name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: success()
    steps:
      - name: Step 2
        run: echo "This is job 2"

  manual-trigger:
    runs-on: ubuntu-latest
    needs: job2
    if: always() && success()
    steps:
      - name: Manual Trigger
        run: echo "Manually triggered job"

