name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      deployDEV:
        description: 'Deploy to DEV'
        required: false
      promoteQA:
        description: 'Promote to QA'
        required: false
      deployQA:
        description: 'Deploy to QA'
        required: false
      signoffQA:
        description: 'Sign off QA'
        required: false
      promoteSTG:
        description: 'Promote to STG'
        required: false
      deploySTG:
        description: 'Deploy to STG'
        required: false
      signoffSTG:
        description: 'Sign off STG'
        required: false

jobs:
  deployDEV:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deployDEV == 'true' }}
    steps:
      - name: Deploy to DEV
        run: echo "Deploying to DEV"

  promoteQA:
    runs-on: ubuntu-latest
    needs: deployDEV
    if: ${{ github.event.inputs.promoteQA == 'true' }}
    steps:
      - name: Promote to QA
        run: echo "Promoting to QA"

  deployQA:
    runs-on: ubuntu-latest
    needs: promoteQA
    if: ${{ github.event.inputs.deployQA == 'true' }}
    steps:
      - name: Deploy to QA
        run: echo "Deploying to QA"

  signoffQA:
    runs-on: ubuntu-latest
    needs: deployQA
    if: ${{ github.event.inputs.signoffQA == 'true' }}
    steps:
      - name: Sign off QA
        run: echo "Signing off QA"

  promoteSTG:
    runs-on: ubuntu-latest
    needs: signoffQA
    if: ${{ github.event.inputs.promoteSTG == 'true' }}
    steps:
      - name: Promote to STG
        run: echo "Promoting to STG"

  deploySTG:
    runs-on: ubuntu-latest
    needs: promoteSTG
    if: ${{ github.event.inputs.deploySTG == 'true' }}
    steps:
      - name: Deploy to STG
        run: echo "Deploying to STG"

  signoffSTG:
    runs-on: ubuntu-latest
    needs: deploySTG
    if: ${{ github.event.inputs.signoffSTG == 'true' }}
    steps:
      - name: Sign off STG
        run: echo "Signing off STG"
