name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      deployDEV:
        description: 'Deploy to DEV'
        required: false
      promoteQA:
        description: 'Promote to QA'
        required: false
      deployQA:
        description: 'Deploy to QA'
        required: false
      signofQA:
        description: 'Sign off QA'
        required: false
      promoteSTG:
        description: 'Promote to STG'
        required: false
      deploySTG:
        description: 'Deploy to STG'
        required: false
      signofSTG:
        description: 'Sign off STG'
        required: false

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run some steps
        run: echo "Running some steps"

      - name: Use the inputs
        run: |
          echo "deployDEV: ${{ github.event.inputs.deployDEV }}"
          echo "promoteQA: ${{ github.event.inputs.promoteQA }}"
          echo "deployQA: ${{ github.event.inputs.deployQA }}"
          echo "signofQA: ${{ github.event.inputs.signofQA }}"
          echo "promoteSTG: ${{ github.event.inputs.promoteSTG }}"
          echo "deploySTG: ${{ github.event.inputs.deploySTG }}"
          echo "signofSTG: ${{ github.event.inputs.signofSTG }}"
