name: Deploy

on:
  workflow_dispatch:
    inputs:
      job-to-run:
        description: 'Select job to run'
        required: true
        default: 'build'
        options:
          - 'build'
          - 'deploy-to-staging'
          - 'deploy-to-production'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Building the application..."
          # Add your build steps here
          # For example, compile code, install dependencies, etc.

  deploy-to-staging:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: staging

    steps:
      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment..."
          # Add your deployment steps here
          # For example, copy files to the server, restart services, etc.
          echo "Deployment to staging complete!"

  deploy-to-production:
    needs: deploy-to-staging
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Deploy to production
        run: |
          echo "Deploying to production environment..."
          # Add your production deployment steps here
          # This could include additional checks or validations
          echo "Deployment to production complete!"
