name: Manual Workflow with Inputs

on:
  workflow_dispatch:
    inputs:
      run-job1:
        description: 'Run Job 1'
        required: true
      run-job2:
        description: 'Run Job 2'
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    if: github.event.inputs.run-job1 == 'true'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Text from Job 1
      run: echo "Hello from Job 1"

  job2:
    runs-on: ubuntu-latest
    if: github.event.inputs.run-job2 == 'true'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Confirm Job 2
      id: confirm
      run: |
        echo "Do you want to proceed with Job 2? (yes/no)"
        read confirmation
        echo "::set-output name=confirmation::$confirmation"

    - name: Print Text from Job 2
      run: |
        if [ "${{ steps.confirm.outputs.confirmation }}" == "yes" ]; then
          echo "Proceeding with Job 2"
        else
          echo "Job 2 canceled"
          exit 1
        fi
