name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      workflowType:
        description: 'Type of workflow to run'
        required: true
        default: 'HA-Internal'
        options: 
            - 'HA-Iternal'
            - 'HA-External'
            - 'DataServices'
            - 'NIFI'

jobs:
  run-workflow:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workflowType: ${{ github.event.inputs.workflowType }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Workflow
        run: |
          if [ "${{ matrix.workflowType }}" = "HA-Iternal" ]; then
            # Trigger the HA-Iternal workflow
            curl -X POST \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/DS.yml/dispatches \
              -d '{"ref":"main"}'
          elif [ "${{ matrix.workflowType }}" = "HA-External" ]; then
            # Add steps to trigger HA-External workflow
            curl -X POST \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/DS.yml/dispatches \
              -d '{"ref":"main"}'
          elif [ "${{ matrix.workflowType }}" = "DataServices" ]; then
            # Add steps to trigger HDataServices workflow
            curl -X POST \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/DS.yml/dispatches \
              -d '{"ref":"main"}'
          else
            echo "Invalid workflowType provided"
            exit 1
          fi
