name: My CI/CD Workflow

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          # Your build commands here
          echo "Building the project"

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Ask for approval
        id: approval
        run: |
          echo "Do you approve this deployment? (yes/no)"
          echo "::set-output name=approved::${{ runner.os == 'Windows' && (INPUT_APPROVE == 'yes' || INPUT_APPROVE == 'no') }}"
        shell: bash

      - name: Run tests if approved
        if: steps.approval.outputs.approved == 'yes'
        run: |
          # Your test commands here
          echo "Running tests"
