name: Manual Trigger with Approval

on:
  workflow_dispatch:
    inputs:
      approval:
        description: 'Approve to run Job2'
        required: true
        default: 'false'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set Approval for Job2
        run: echo "APPROVAL=${{ github.event.inputs.approval }}" >> $GITHUB_ENV
      - name: Job 1
        run: echo "Running Job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ env.APPROVAL == 'true' }}
    steps:
      - name: Job 2
        run: echo "Running Job 2"
