name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      run-job1:
        description: 'Run Job 1'
        required: false
        default: 'true'
      run-job2:
        description: 'Run Job 2'
        required: false
        default: 'true'

jobs:
  job1:
    runs-on: ubuntu-latest
    if: github.event.inputs.run-job1 == 'true'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Text from Job 1
      run: echo "Hello from Job 1"

  job2:
    runs-on: ubuntu-latest
    if: github.event.inputs.run-job2 == 'true'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Text from Job 2
      run: echo "Hello from Job 2"
