name: DD agent sample

on:
  workflow_dispatch:
    inputs:
      Cluster_Type:
        description: 'Cluster Type'
        required: true
        default: 'DP'
        options:
          - 'DP'
          - 'NGC'
      Region:
        description: 'Select Region'
        required: true
        default: 'US'
        options:
          - 'US'
          - 'WE'
          - 'AU'
          - 'SG'
      Environment:
        description: 'Environment'
        required: true
        default: 'DEV'
        options:
          - 'DEV'
          - 'QA'
          - 'UAT'
          - 'STG'
          - 'PRD'

jobs:
  ClusterType:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cluster Type DP | NGC
        run: |
          echo "${{ inputs.Cluster_Type }}"

  DP:
    runs-on: ubuntu-latest
    environment:
      name: DP    
    needs: ClusterType
    if: "${{ inputs.Cluster_Type == 'DP' }}"
    steps:
      - name: DP Cluster  
        run: |
          echo "${{ inputs.Cluster_Type }}"
          echo "${{ github.event_name }}"
  NGC:
    runs-on: ubuntu-latest
    environment:
      name: NGC    
    needs: ClusterType
    if: "${{ inputs.Cluster_Type == 'NGC' }}"
    steps:
      - name: DP Cluster  
        run: |
          echo "${{ inputs.Cluster_Type }}"
  DEV:
    runs-on: ubuntu-latest  
    needs: DP
    if: "${{ inputs.Environment == 'DEV' }}"
    steps:
      - name: Deploy to Dev
        run: |
          echo "${{ inputs.Environment }}"

  PromoteDPUSQA:
    runs-on: ubuntu-latest
    needs: [DP, DEV]
    if: >
      success() && (needs.DP.result == 'success' || needs.DEV.result == 'success' || inputs.Environment == 'QA')
    steps:
      - name: Promote DP US DEV to QA
        run: |
          echo "Promoting DP US DEV to QA" 
          
  QA:
    runs-on: ubuntu-latest
    needs: [PromoteDPUSQA, DP]
    if: >
      success() && (needs.PromoteDPUSQA.result == 'success' || needs.PromoteDPUSQA.result == 'success')
    steps:
      - name: Deploy to QA
        run: |
          echo "${{ inputs.Environment }}"
                   
  NGC_DEV:
    runs-on: ubuntu-latest  
    needs: NGC
    if: "${{ inputs.Environment == 'DEV' }}"
    steps:
      - name: Deploy to Dev
        run: |
          echo "${{ inputs.Environment }}"  
  NGC_QA:
    runs-on: ubuntu-latest  
    needs: NGC_DEV
    if: "${{ inputs.Environment == 'QA' }}"
    steps:
      - name: Deploy to QA
        run: |
          echo "${{ inputs.Environment }}"           
