name: Hello World Workflow

on:
  workflow_run:
    workflows: ["Dynamic Greeting Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: before checkout
        run: pwd
        
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: after checkout
        run: pwd
