name: Deploy Datadog Agent on DS AKS Clusters (Dev & QA)
run-name: ${{ github.actor }} is Datadog Agent on DS AKS Clusters from ${{ github.ref_name }} branch
on:
  workflow_dispatch:
    inputs:
        deploy-all:
          description: 'DEPLOY ALL CLUSTERS'
          type: boolean
          required: false
          default: true
        us-lower:
          description: 'US LOWER'
          type: boolean
          required: false
          default: true
        non-prd:
          description: 'NON-PRD'
          type: boolean
          required: false
          default: true
        prd:
          description: 'PRD'
          type: boolean
          required: false
          default: true                
        us-dev-deploy:
          description: 'US DEV DEPLOY'
          type: boolean
          required: false
          default: ${{ github.event.inputs.us-lower }}
        us-qa-deploy:
          description: 'US QA DEPLOY'
          type: boolean
          required: false
          default: ${{ github.event.inputs.us-lower }}        
        us-stg-deploy:
          description: 'US STG DEPLOY'
          type: boolean
          required: false
          default: false
        we-stg-deploy:
          description: 'WE STG DEPLOY'
          type: boolean
          required: false
          default: false
        us-prd-deploy:
          description: 'US PRD DEPLOY'
          type: boolean
          required: false
          default: false
        we-prd-deploy:
          description: 'WE PRD DEPLOY'
          type: boolean
          required: false
          default: false                       
jobs:
  DEPLOY_ALL:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deploy-all == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  US_LOWER:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.us-lower == 'true' || github.event.inputs.deploy-all == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  NON_PRD:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.non-prd == 'true' || github.event.inputs.deploy-all == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  PRD:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.prd == 'true' || github.event.inputs.deploy-all == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2                

  US_DEV_DEPLOY:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.us-dev-deploy == 'true' || github.event.inputs.deploy-all == 'true' || github.event.inputs.us-lower == 'true' }}
    needs: US_LOWER
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  US_QA_DEPLOY:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.us-qa-deploy == 'true' || github.event.inputs.deploy-all == 'true' || github.event.inputs.us-lower == 'true' }}
    needs: US_LOWER
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        ##Clear all kubeconfigs
        ##fetch QA Kubeconfig
        ##validate QA kubeconfig

  US_STG_DEPLOY:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.us-stg-deploy == 'true' || github.event.inputs.deploy-all == 'true' }}
    needs: NON_PRD     
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        ##Clear all kubeconfigs
        ##fetch QA Kubeconfig
        ##validate QA kubeconfig

  WE_STG_DEPLOY:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.we-stg-deploy == 'true' || github.event.inputs.deploy-all == 'true' }}
    needs: NON_PRD
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        ##Clear all kubeconfigs
        ##fetch QA Kubeconfig
        ##validate QA kubeconfig

  US_PRD_DEPLOY:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.us-prd-deploy == 'true' || github.event.inputs.deploy-all == 'true' }}
    needs: PRD 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        ##Clear all kubeconfigs
        ##fetch QA Kubeconfig
        ##validate QA kubeconfig

  WE_PRD_DEPLOY:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.we-prd-deploy == 'true' || github.event.inputs.deploy-all == 'true' }}
    needs: PRD       
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        ##Clear all kubeconfigs
        ##fetch QA Kubeconfig
        ##validate QA kubeconfig
