name: Deploy Datadog Agent on DS AKS Clusters (Dev & QA)
run-name: ${{ github.actor }} is Datadog Agent on DS AKS Clusters from ${{ github.ref_name }} branch
on:
  workflow_dispatch:
    inputs:
        us-dev-deploy:
          description: 'US DEV DEPLOY'
          type: boolean
          required: true
          default: false
        us-qa-deploy:
          description: 'US QA DEPLOY'
          type: boolean
          required: true
          default: false          
        us-stg-deploy:
          description: 'US STG DEPLOY'
          type: boolean
          required: true
          default: false
        we-stg-deploy:
          description: 'WE STG DEPLOY'
          type: boolean
          required: true
          default: false
        us-prd-deploy:
          description: 'US PRD DEPLOY'
          type: boolean
          required: true
          default: false
        we-prd-deploy:
          description: 'WE PRD DEPLOY'
          type: boolean
          required: true
          default: false          
        au-prd-deploy:
          description: 'AU PRD DEPLOY'
          type: boolean
          required: true
          default: false
        SG-PRD-deploy:
          description: 'SG PRD DEPLOY'
          type: boolean
          required: true
          default: false          
jobs:
  US DEV DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        ##Clear all kubeconfigs
        ##validate Dev kubeconfig

  US QA DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        ##Clear all kubeconfigs
        ##fetch QA Kubeconfig
        ##validate QA kubeconfig

  US STG DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        ##Clear all kubeconfigs
        ##fetch QA Kubeconfig
        ##validate QA kubeconfig

  WE STG DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        ##Clear all kubeconfigs
        ##fetch QA Kubeconfig
        ##validate QA kubeconfig

  US PRD DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        ##Clear all kubeconfigs
        ##fetch QA Kubeconfig
        ##validate QA kubeconfig

  WE PRD DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        ##Clear all kubeconfigs
        ##fetch QA Kubeconfig
        ##validate QA kubeconfig

  AU PRD DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        ##Clear all kubeconfigs
        ##fetch QA Kubeconfig
        ##validate QA kubeconfig

  SG PRD DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        ##Clear all kubeconfigs
        ##fetch QA Kubeconfig
        ##validate QA kubeconfig
