name: Install Datadog Agent

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev or qa)'
        required: true
        default: 'dev'

jobs:
  install-datadog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Azure CLI
        uses: azure/setup-az-cli@v1
        with:
          azcliversion: 'latest'

      - name: Fetch AKS cluster config from Vault
        run: |
          VAULT_ADDR="https://your-vault-url"

          # Use different role IDs and secret IDs based on the specified environment
          ROLE_ID=$(vault read -field=role_id auth/approle/role/your-role-id-${{ github.event.inputs.environment }}/role-id)
          SECRET_ID=$(vault write -field=secret_id -f auth/approle/role/your-role-id-${{ github.event.inputs.environment }}/secret-id)

          export KUBECONFIG=$(vault read -field=kubeconfig secret/path/to/aks-cluster/${{ github.event.inputs.environment }} role_id=${ROLE_ID} secret_id=${SECRET_ID})
          echo "$KUBECONFIG" > kubeconfig.yaml

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          mv kubeconfig.yaml ~/.kube/config

      - name: Install Datadog Helm chart
        run: |
          helm repo add datadog https://helm.datadoghq.com
          helm repo update

          # Use different values for apiKey and other parameters based on the specified environment
          helm upgrade --install datadog-agent datadog/datadog \
            --namespace datadog \
            --set datadog.apiKey=${{ secrets.DATADOG_API_KEY_${{ github.event.inputs.environment | upper }} }}

