name: Install Datadog Agent

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'Choose the cluster to install Datadog Agent (dev/qa)'
        required: true
        default: 'dev'

jobs:
  install-datadog-agent-dev:
    runs-on: ubuntu-latest
    if: github.event.inputs.cluster == 'dev'

    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      VAULT_URL: ${{ secrets.VAULT_DEV_URL }}
      VAULT_ROLE_ID: ${{ secrets.VAULT_DEV_ROLE_ID }}
      VAULT_SECRET_ID: ${{ secrets.VAULT_DEV_SECRET_ID }}
      VAULT_KUBECONFIG_PATH: ${{ secrets.VAULT_DEV_KUBECONFIG_PATH }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ env.VAULT_KUBECONFIG_PATH }}
        version: 'latest'

    - name: Authenticate with Vault
      run: |
        export VAULT_TOKEN=$(curl -s --request POST --data "{\"role_id\":\"${VAULT_ROLE_ID}\",\"secret_id\":\"${VAULT_SECRET_ID}\"}" ${VAULT_URL}/v1/auth/approle/login | jq -r .auth.client_token)
        echo "VAULT_TOKEN=${VAULT_TOKEN}" >> $GITHUB_ENV

    - name: Install Datadog Helm Chart on Dev
      run: |
        helm repo add datadog https://helm.datadoghq.com
        helm repo update
        helm upgrade --install datadog-agent datadog/datadog \
          --namespace default \
          --set datadog.apiKey=${DATADOG_API_KEY} \
          --kube-context dev

  install-datadog-agent-qa:
    runs-on: ubuntu-latest
    if: github.event.inputs.cluster == 'qa'

    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      VAULT_URL: ${{ secrets.VAULT_QA_URL }}
      VAULT_ROLE_ID: ${{ secrets.VAULT_QA_ROLE_ID }}
      VAULT_SECRET_ID: ${{ secrets.VAULT_QA_SECRET_ID }}
      VAULT_KUBECONFIG_PATH: ${{ secrets.VAULT_QA_KUBECONFIG_PATH }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ env.VAULT_KUBECONFIG_PATH }}
        version: 'latest'

    - name: Authenticate with Vault
      run: |
        export VAULT_TOKEN=$(curl -s --request POST --data "{\"role_id\":\"${VAULT_ROLE_ID}\",\"secret_id\":\"${VAULT_SECRET_ID}\"}" ${VAULT_URL}/v1/auth/approle/login | jq -r .auth.client_token)
        echo "VAULT_TOKEN=${VAULT_TOKEN}" >> $GITHUB_ENV

    - name: Install Datadog Helm Chart on QA
      run: |
        helm repo add datadog https://helm.datadoghq.com
        helm repo update
        helm upgrade --install datadog-agent datadog/datadog \
          --namespace default \
          --set datadog.apiKey=${DATADOG_API_KEY} \
          --kube-context qa
