name: Welcome Workflow

on:
  workflow_run:
    workflows: ["Dynamic Greeting Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Welcome
        run: echo "Welcome to GitHub Actions!"
